wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 32
beta:
  value: 0.95
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum:
  value: 0.9
num_hlayers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 0.05
weight_init:
  value: random
