wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 16
beta:
  value: 0.95
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.0004
loss:
  value: cross_entropy
momentum:
  value: 0.9
num_hlayers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0.1
weight_init:
  value: random
