wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 128
beta:
  value: 0.95
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.9
num_hlayers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 0.1
weight_init:
  value: xavier
