wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1678995368.484218
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 15
      - 16
      - 17
      - 23
      - 37
      4: 3.9.16
      5: 0.13.10
      8:
      - 5
    visualize:
      confusion matrix 1:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: confusion matrix 1_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
activation_function:
  desc: null
  value: leakyrelu
batch_size:
  desc: null
  value: 128
beta:
  desc: null
  value: 0.95
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.999
dataset:
  desc: null
  value: fashion_mnist
epochs:
  desc: null
  value: 0
epsilon:
  desc: null
  value: 1.0e-08
hidden_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0004
loss:
  desc: null
  value: cross_entropy
momentum:
  desc: null
  value: 0.9
num_hlayers:
  desc: null
  value: 5
optimizer:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0.05
weight_init:
  desc: null
  value: xavier
